classDiagram
    Usuario <|-- Membro
    Usuario <|-- Administrador
    Usuario: +String email
    Usuario : +String senha
    Usuario: +consultarCatalogo()
    Usuario: +fazerLogin()
    Usuario: +realizarEmprestimo()
    Animal: +mate()
    class Membro{
      +String beakColor
      +swim()
      +quack()
    }
    class Administrador{
      -int sizeInFeet
      -canEat()
    }
    class Zebra{
      +bool is_wild
      +run()
    }